using System.Reflection;
using UnityEngine;

namespace ChatChaos.Networking
{
    /// <summary>
    /// Standard Lethal Company community snippet. On load, it scans the assembly and
    /// calls the methods generated by the "Netcode Patcher" that register the RPCs.
    /// Without this trigger, the [ServerRpc]/[ClientRpc] methods are not bound to the
    /// network.
    ///
    /// ⚠️ This does NOT replace the Netcode Patcher: the .dll must STILL be patched
    /// after compilation (the GitHub workflow does it, see README). This code only
    /// activates what the tool generated.
    /// </summary>
    public static class NetcodePatcher
    {
        [RuntimeInitializeOnLoadMethod]
        private static void Init()
        {
            var types = Assembly.GetExecutingAssembly().GetTypes();
            foreach (var type in types)
            {
                var methods = type.GetMethods(
                    BindingFlags.NonPublic | BindingFlags.Public |
                    BindingFlags.Static | BindingFlags.Instance);

                foreach (var method in methods)
                {
                    var attribs = method.GetCustomAttributes(
                        typeof(RuntimeInitializeOnLoadMethodAttribute), false);
                    if (attribs.Length > 0 && method.Name != nameof(Init))
                        method.Invoke(null, null);
                }
            }
        }
    }
}
